name: burr
favicon: null
layout_spectrum: 0.4476302172988653
typography_spectrum: 0.6699601986911148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.36477901926264167
  lightness: 0.10661671846173704
  saturation: 0.3356249837670475
  rhythmicContrast: 0.2050275020301342
purpose: []
